IBM HR Analytics Employee Attrition & Performance

Importation

In [95]:
import pandas as pd
import matplotlib.pyplot as plt

In [96]:
#Read The Dataset File
df = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [97]:
df = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [98]:
#Display First 5 rows
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [99]:
#Display Last 5 rows
df.tail()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [100]:
#Rows and columns Count
df.shape

(1470, 35)

In [101]:
#Columns Names
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [102]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 402.1 KB

In [103]:
df.dtypes

Age                         int64
Attrition                     str
BusinessTravel                str
DailyRate                   int64
Department                    str
DistanceFromHome            int64
Education                   int64
EducationField                str
EmployeeCount               int64
EmployeeNumber              int64
EnvironmentSatisfaction     int64
Gender                        str
HourlyRate                  int64
JobInvolvement              int64
JobLevel                    int64
JobRole                       str
JobSatisfaction             int64
MaritalStatus                 str
MonthlyIncome               int64
MonthlyRate                 int64
NumCompaniesWorked          int64
Over18                        str
OverTime                      str
PercentSalaryHike           int64
PerformanceRating           int64
RelationshipSatisfaction    int64
StandardHours               int64
StockOptionLevel            int64
TotalWorkingYears           int64
TrainingTimesLastYear       int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsInCurrentRole          int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

In [104]:
#Check Missing values
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [105]:
#check duplicates
df.duplicated().sum()

np.int64(0)

In [106]:
df.nunique()

Age                           43
Attrition                      2
BusinessTravel                 3
DailyRate                    886
Department                     3
DistanceFromHome              29
Education                      5
EducationField                 6
EmployeeCount                  1
EmployeeNumber              1470
EnvironmentSatisfaction        4
Gender                         2
HourlyRate                    71
JobInvolvement                 4
JobLevel                       5
JobRole                        9
JobSatisfaction                4
MaritalStatus                  3
MonthlyIncome               1349
MonthlyRate                 1427
NumCompaniesWorked            10
Over18                         1
OverTime                       2
PercentSalaryHike             15
PerformanceRating              2
RelationshipSatisfaction       4
StandardHours                  1
StockOptionLevel               4
TotalWorkingYears             40
TrainingTimesLastYear          7
WorkLifeBalance                4
YearsAtCompany                37
YearsInCurrentRole            19
YearsSinceLastPromotion       16
YearsWithCurrManager          18
dtype: int64

In [107]:
df["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [108]:
df["Attrition"].value_counts(normalize=True) * 100

Attrition
No     83.877551
Yes    16.122449
Name: proportion, dtype: float64

In [109]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

Cleaning

In [110]:
df_raw = df.copy()

In [111]:
#Drop the useless Columns
df = df.drop(columns=["EmployeeCount", "Over18", "StandardHours"])

In [112]:
df.shape

(1470, 32)

Feature Engineering

In [113]:
education_map = {
    1: "Below College",
    2: "College",
    3: "Bachelor",
    4: "Master",
    5: "Doctor"
}
df["EducationLevel"] = df["Education"].map(education_map)

In [114]:
environment_map = {
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
}
df["EnvironmentSatisfactionLevel"] = (
    df["EnvironmentSatisfaction"].map(environment_map)
)

In [115]:
job_involvement_map = {
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
}
df["JobInvolvementLevel"] = (
    df["JobInvolvement"].map(job_involvement_map)
)

In [116]:
joblevel_map = {
    1: "Junior",
    2: "Mid-Level",
    3: "Senior",
    4: "Senior",
    5: "Senior"
}

df["JobLevelCategory"] = df["JobLevel"].map(joblevel_map)

In [117]:
def companies_category(x):
    if x == 0:
        return "No Previous Companies"
    elif x <= 2:
        return "1-2 Companies"
    elif x <= 4:
        return "3-4 Companies"
    else:
        return "5+ Companies"

df["PreviousCompaniesCategory"] = df["NumCompaniesWorked"].apply(
    companies_category
)

In [118]:
def experience_category(x):
    if x <= 2:
        return "0-2 Years"
    elif x <= 5:
        return "3-5 Years"
    elif x <= 10:
        return "6-10 Years"
    elif x <= 20:
        return "11-20 Years"
    else:
        return "21+ Years"

df["TotalExperienceCategory"] = df["TotalWorkingYears"].apply(
    experience_category
)

In [119]:
worklife_map = {
    1: "Bad",
    2: "Good",
    3: "Very Good",
    4: "Excellent"
}
df["WorkLifeBalanceLevel"] = df["WorkLifeBalance"].map(worklife_map)

In [120]:
job_satisfaction_map = {
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
}
df["JobSatisfactionLevel"] = df["JobSatisfaction"].map(job_satisfaction_map)

In [121]:
relationship_satisfaction_map = {
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
}
df["RelationshipSatisfactionLevel"] = df["RelationshipSatisfaction"].map(relationship_satisfaction_map)

In [122]:
environment_satisfaction_map = {
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
}
df["EnvironmentSatisfactionLevel"] = df["EnvironmentSatisfaction"].map(environment_satisfaction_map)

In [123]:
job_involvement_map = {
    1: "Low",
    2: "Medium",
    3: "High",
    4: "Very High"
}
df["JobInvolvementLevel"] = df["JobInvolvement"].map(job_involvement_map)

In [124]:
def age_category(age):
    if age <= 25:
        return "18-25"
    elif age <= 35:
        return "26-35"
    elif age <= 45:
        return "36-45"
    elif age <= 55:
        return "46-55"
    else:
        return "56+"
df["AgeCategory"] = df["Age"].apply(age_category)

In [125]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,EducationLevel,EnvironmentSatisfactionLevel,JobInvolvementLevel,JobLevelCategory,PreviousCompaniesCategory,TotalExperienceCategory,WorkLifeBalanceLevel,JobSatisfactionLevel,RelationshipSatisfactionLevel,AgeCategory
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,College,Medium,High,Mid-Level,5+ Companies,6-10 Years,Bad,Very High,Low,36-45
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,Below College,High,Medium,Mid-Level,1-2 Companies,6-10 Years,Very Good,Medium,Very High,46-55
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,College,Very High,Medium,Junior,5+ Companies,6-10 Years,Very Good,High,Medium,36-45
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,Master,Very High,High,Junior,1-2 Companies,6-10 Years,Very Good,High,High,26-35
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,Below College,Low,High,Junior,5+ Companies,6-10 Years,Very Good,Medium,Very High,26-35

After Update

In [126]:
df.shape

(1470, 42)

In [127]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,EducationLevel,EnvironmentSatisfactionLevel,JobInvolvementLevel,JobLevelCategory,PreviousCompaniesCategory,TotalExperienceCategory,WorkLifeBalanceLevel,JobSatisfactionLevel,RelationshipSatisfactionLevel,AgeCategory
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,...,College,Medium,High,Mid-Level,5+ Companies,6-10 Years,Bad,Very High,Low,36-45
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2,3,...,Below College,High,Medium,Mid-Level,1-2 Companies,6-10 Years,Very Good,Medium,Very High,46-55
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,...,College,Very High,Medium,Junior,5+ Companies,6-10 Years,Very Good,High,Medium,36-45
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,5,4,...,Master,Very High,High,Junior,1-2 Companies,6-10 Years,Very Good,High,High,26-35
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,7,1,...,Below College,Low,High,Junior,5+ Companies,6-10 Years,Very Good,Medium,Very High,26-35

In [128]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager', 'EducationLevel',
       'EnvironmentSatisfactionLevel', 'JobInvolvementLevel',
       'JobLevelCategory', 'PreviousCompaniesCategory',
       'TotalExperienceCategory', 'WorkLifeBalanceLevel',
       'JobSatisfactionLevel', 'RelationshipSatisfactionLevel', 'AgeCategory'],
      dtype='str')

In [129]:
df.info

<bound method DataFrame.info of       Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales
1      49        No  Travel_Frequently        279  Research & Development
2      37       Yes      Travel_Rarely       1373  Research & Development
3      33        No  Travel_Frequently       1392  Research & Development
4      27        No      Travel_Rarely        591  Research & Development
...   ...       ...                ...        ...                     ...
1465   36        No  Travel_Frequently        884  Research & Development
1466   39        No      Travel_Rarely        613  Research & Development
1467   27        No      Travel_Rarely        155  Research & Development
1468   49        No  Travel_Frequently       1023                   Sales
1469   34        No      Travel_Rarely        628  Research & Development

      DistanceFromHome  Education EducationField  EmployeeNumber  \
0                    1          2  Life Sciences               1
1                    8          1  Life Sciences               2
2                    2          2          Other               4
3                    3          4  Life Sciences               5
4                    2          1        Medical               7
...                ...        ...            ...             ...
1465                23          2        Medical            2061
1466                 6          1        Medical            2062
1467                 4          3  Life Sciences            2064
1468                 2          3        Medical            2065
1469                 8          3        Medical            2068

      EnvironmentSatisfaction  ... EducationLevel  \
0                           2  ...        College
1                           3  ...  Below College
2                           4  ...        College
3                           4  ...         Master
4                           1  ...  Below College
...                       ...  ...            ...
1465                        3  ...        College
1466                        4  ...  Below College
1467                        2  ...       Bachelor
1468                        4  ...       Bachelor
1469                        2  ...       Bachelor

      EnvironmentSatisfactionLevel  JobInvolvementLevel  JobLevelCategory  \
0                           Medium                 High         Mid-Level
1                             High               Medium         Mid-Level
2                        Very High               Medium            Junior
3                        Very High                 High            Junior
4                              Low                 High            Junior
...                            ...                  ...               ...
1465                          High            Very High         Mid-Level
1466                     Very High               Medium            Senior
1467                        Medium            Very High         Mid-Level
1468                     Very High               Medium         Mid-Level
1469                        Medium            Very High         Mid-Level

     PreviousCompaniesCategory  TotalExperienceCategory WorkLifeBalanceLevel  \
0                 5+ Companies               6-10 Years                  Bad
1                1-2 Companies               6-10 Years            Very Good
2                 5+ Companies               6-10 Years            Very Good
3                1-2 Companies               6-10 Years            Very Good
4                 5+ Companies               6-10 Years            Very Good
...                        ...                      ...                  ...
1465             3-4 Companies              11-20 Years            Very Good
1466             3-4 Companies               6-10 Years            Very Good
1467             1-2 Companies               6-10 Years            Very Good
1468             1-2 Companies              11-20 Years                 Good
1469             1-2 Companies               6-10 Years            Excellent

      JobSatisfactionLevel  RelationshipSatisfactionLevel  AgeCategory
0                Very High                            Low        36-45
1                   Medium                      Very High        46-55
2                     High                         Medium        36-45
3                     High                           High        26-35
4                   Medium                      Very High        26-35
...                    ...                            ...          ...
1465             Very High                           High        36-45
1466                   Low                            Low        36-45
1467                Medium                         Medium        26-35
1468                Medium                      Very High        46-55
1469                  High                            Low        26-35

[1470 rows x 42 columns]>

In [130]:
for i, col in enumerate(df.columns, start=1):
    print(i, col)

1 Age
2 Attrition
3 BusinessTravel
4 DailyRate
5 Department
6 DistanceFromHome
7 Education
8 EducationField
9 EmployeeNumber
10 EnvironmentSatisfaction
11 Gender
12 HourlyRate
13 JobInvolvement
14 JobLevel
15 JobRole
16 JobSatisfaction
17 MaritalStatus
18 MonthlyIncome
19 MonthlyRate
20 NumCompaniesWorked
21 OverTime
22 PercentSalaryHike
23 PerformanceRating
24 RelationshipSatisfaction
25 StockOptionLevel
26 TotalWorkingYears
27 TrainingTimesLastYear
28 WorkLifeBalance
29 YearsAtCompany
30 YearsInCurrentRole
31 YearsSinceLastPromotion
32 YearsWithCurrManager
33 EducationLevel
34 EnvironmentSatisfactionLevel
35 JobInvolvementLevel
36 JobLevelCategory
37 PreviousCompaniesCategory
38 TotalExperienceCategory
39 WorkLifeBalanceLevel
40 JobSatisfactionLevel
41 RelationshipSatisfactionLevel
42 AgeCategory

In [131]:
columns_to_drop = [
    "Education",
    "EnvironmentSatisfaction",
    "JobInvolvement",
    "JobLevel",
    "NumCompaniesWorked",
    "TotalWorkingYears",
    "WorkLifeBalance",
    "JobSatisfaction",
    "RelationshipSatisfaction"
]
df = df.drop(columns=columns_to_drop)

In [133]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,EducationField,EmployeeNumber,Gender,HourlyRate,...,EducationLevel,EnvironmentSatisfactionLevel,JobInvolvementLevel,JobLevelCategory,PreviousCompaniesCategory,TotalExperienceCategory,WorkLifeBalanceLevel,JobSatisfactionLevel,RelationshipSatisfactionLevel,AgeCategory
0,41,Yes,Travel_Rarely,1102,Sales,1,Life Sciences,1,Female,94,...,College,Medium,High,Mid-Level,5+ Companies,6-10 Years,Bad,Very High,Low,36-45
1,49,No,Travel_Frequently,279,Research & Development,8,Life Sciences,2,Male,61,...,Below College,High,Medium,Mid-Level,1-2 Companies,6-10 Years,Very Good,Medium,Very High,46-55
2,37,Yes,Travel_Rarely,1373,Research & Development,2,Other,4,Male,92,...,College,Very High,Medium,Junior,5+ Companies,6-10 Years,Very Good,High,Medium,36-45
3,33,No,Travel_Frequently,1392,Research & Development,3,Life Sciences,5,Female,56,...,Master,Very High,High,Junior,1-2 Companies,6-10 Years,Very Good,High,High,26-35
4,27,No,Travel_Rarely,591,Research & Development,2,Medical,7,Male,40,...,Below College,Low,High,Junior,5+ Companies,6-10 Years,Very Good,Medium,Very High,26-35

In [132]:
df.shape

(1470, 33)